name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Possibly Skip?
      uses: veggiemonk/skip-commit@master
      env:
        COMMIT_FILTER: skip-ci

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Gradle Clean?
      run: ./gradlew clean

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Build
      uses: actions/upload-artifact@master
      with:
        name: Build Output
        path: build/libs
